ecmwf/eckit

CMakeLists.txt

`ecbuild_add_option(FEATURE MPI ...)` creates variable `HAVE_MPI` but this conditional checks `HAVE_ECKIT_MPI` which is never set.  With this patch, `${CMAKE_INSTALL_PREFIX}/lib/cmake/eckit/eckit-config.cmake` now correctly includes `eckit_mpi` in `ECKIT_LIBRARIES` when MPI is found.

Fix missing eckit_mpi.so in ECKIT_LIBRARIES

---

src/eckit/sql/sqly.y

With `/usr/bin/yacc` provided by the newest GNU bison/3.7.1, the `src/eckit/sql/sqly.y` yacc file is not compatible and is generating yacc warnings and a compilation failure for a missing symbol `yyscan_t`:
```
/usr/bin/x86_64-pc-linux-gnu-g++ -Deckit_sql_EXPORTS -I/var/tmp/portage/sci-libs/eckit-1.10.1.2/work/eckit-1.10.1.2/src -Isrc -I/var/tmp/portage/sci-libs/eckit-1.10.1.2/work/eckit-1.10.1.2/src/eckit/sql -I/var/tmp/portage/sci-libs/eckit-1.10.1.2/work/eckit-1.10.1.2/src/eckit -I/usr/include/eigen3  -O2 -pipe -pipe -O3 -DNDEBUG -fPIC -std=gnu++11 -Wno-unused-function -Wno-sign-compare -MD -MT src/eckit/sql/CMakeFiles/eckit_sql.dir/SQLParser.cc.o -MF src/eckit/sql/CMakeFiles/eckit_sql.dir/SQLParser.cc.o.d -o src/eckit/sql/CMakeFiles/eckit_sql.dir/SQLParser.cc.o -c …
```

Update sqly.y for modern GNU bison-3.7.1 support

---

src/eckit/mpi/DataType.cc

This is a minor PR to add the std::complex<double> datatype to mpi/DataType.cc. The code for this already exists in DataType.h, so the changes here are minimal.

Added std::complex<double> to mpi/DataType.cc.

---

src/eckit/parser/YAMLParser.cc
tests/parser/test_yaml.cc

The YAML parser currently treats values such as `1e-5`, `123.` or `.123` as strings.
[The YAML specification](https://yaml.org/spec/1.2/spec.html#id2805071) recommends treating such values as numbers. This PR modifies the regular expression used to recognise floating-point numbers so that it matches these kinds of values.

YAML parser: recognise a wider range of floating-point literals

---

src/eckit/exception/Exceptions.h

Currently `Assert()` takes the message to be displayed if the assertion fails by const reference to an `std::string`. This function is called by the `ASSERT()` macro, which converts its argument to a string literal and passes it to `Assert()`. As a result, a `std::string` object is created and destroyed in each call to `ASSERT()`. This can be quite costly if the macro is called from a tight loop and its argument is long enough to incur a heap allocation and deallocation in the constructor and destructor of `std::string`.
This PR adds an overload of `Assert()` taking a `const char*`; this makes the `ASSERT()` macro much cheaper to call. For example, this simple change reduces from 27 s to 10 s the time taken by
```
odc sql "select *" -i atms6K.odb -o /dev/null -f odb
```
where `atms6K.odb` …

Add an overload of Assert() taking a const char* rather than a const std::string&

---

src/eckit/parser/YAMLParser.cc
tests/parser/test_yaml.cc

This change ensures that quoted associative array entry keys in _block style_ are parsed correctly by the YAML parser. For example, consider the data where we have to use number-like strings as associative array keys. We have to quote the numbers like this:
```yaml
"10": ten
"20": twenty
```
which should be equivalent to:
```yaml
{"10": "ten", "20": "twenty"}
```
The parser did not parse the _block style_ version correctly before this change.

YAML parser: handle block style quoted associative array key

---

.github/workflows/ci.yml
.github/workflows/reusable-ci-hpc.yml
.github/workflows/reusable-ci.yml

CI is triggered by push event or pull request, builds and tests the current repository.

Enable CI on self-hosted runners

---

.github/workflows/ci.yml
.github/workflows/label-public-pr.yml

CI for pull requests originating from forks will run only when labeled with `approved-for-ci` label. Label `contributor` will be added to such PRs. Label `approved-for-ci` will be removed whenever contents of the PR change. 
CI for pull requests from internal branches will run the same way as before.

Fix CI for public pull requests

---

.github/workflows/ci.yml
.github/workflows/reusable-ci-hpc.yml
.github/workflows/reusable-ci.yml

Run CI including public and private downstream packages on self-hosted runners and HPC.

Switch Eckit to downstream CI

---

.github/workflows/ci.yml

`success() || failure()` is not enough, it would trigger even if previous job is skipped, i.e. unlabeled PRs.

Add trigger condition for all CI jobs

---

src/eckit/geometry/CMakeLists.txt
src/eckit/geometry/CoordinateHelpers.cc
src/eckit/geometry/CoordinateHelpers.h
src/eckit/geometry/EllipsoidOfRevolution.cc
src/eckit/geometry/EllipsoidOfRevolution.h
src/eckit/geometry/Sphere.cc
src/eckit/geometry/Sphere.h
src/eckit/geometry/SphereT.h
src/eckit/geometry/polygon/LonLatPolygon.cc
src/eckit/geometry/polygon/LonLatPolygon.h
tests/geometry/CMakeLists.txt
tests/geometry/test_coordinate_helpers.cc
tests/geometry/test_polygon.cc
tests/geometry/test_sphere.cc

The atlas library generates points with latitudes outside the usual [-90°, 90°] interval, for example halo points on a regular Gaussian grid. Passing these points through eckit's `convertSphericalToCartesian` throws an exception because the code expects latitudes within the usual interval.
This PR preserves the current default behavior, but adds the option to renormalise points with latitudes "across the pole".
(I'd be happy to update the PR to remove the bool and always apply the renormalisation, if that is the preferred behavior. This would enable the change to propagate transparently to atlas without adding the bool, but would affect users who relied on the exception for points outside [-90,90]).

Enable convertSphericalToCartesian to handle latitudes across poles

---

.github/ci-hpc-config.yml

Adds build configurations to build with and without MPI on the HPC.

Add MPI on/off to build matrix

---

src/eckit/system/LibraryManager.cc
src/eckit/system/LibraryManager.h

The development of plugins is designed with default following structure:
```
<plugin-path>/share/plugins/manifest.yml
<plugin-path>/lib/lib<plugin>.so
```
This PR creates a function `LibraryManager::addPluginSearchPath( path )`, where `path` is a colon-separated list.
The plugin search paths are then also used for the manifest-scan-path and the dynamic-library-path.

Add possibility to add plugin search paths

---

.clang-format

This pull requests removes problematic duplicate keys from clang-format configuration.
The issue was detected because some IDEs (e.g. CLion) check the .clang-format content, and highlight duplicate keys as an error.

Remove duplicate keys from .clang-format

---

src/eckit/option/CMakeLists.txt
src/eckit/option/CmdArgs.cc
src/eckit/option/FactoryOption.cc
src/eckit/option/FactoryOption.h
src/eckit/option/MultiValueOption.cc
src/eckit/option/MultiValueOption.h
src/eckit/option/Option.cc
src/eckit/option/Option.h
src/eckit/option/Separator.cc
src/eckit/option/Separator.h
src/eckit/option/SimpleOption.cc
src/eckit/option/SimpleOption.h
src/eckit/option/VectorOption.cc
src/eckit/option/VectorOption.h
src/eckit/utils/Tokenizer.h
tests/option/CMakeLists.txt
tests/option/eckit_test_option_cmdargs.cc

This pull request enables the support for multi-value options in CmdArgs.
A multi-value Option allows collecting multiple argv values, as if these values where positional relative to the option e.g. `--option <command> <name> <value> /path/to/one /path/to/two ... --next`.
The goal is to allow collecting argv values until: 1) there are no more values to collect, either because the end of the list of values was reached or because the next option was found; or, 2) a mandatory+optional number of values has been collected.

ECKIT-620 Enable multi-value options in CmdArgs

---

src/eckit/system/ResourceUsage.h

Adding #include <cstddef> suppresses the compilation error `error: unknown type name 'size_t'` issued by Clang 17 on macOS.

Add missing #include<cstddef>

---

src/eckit/CMakeLists.txt
src/eckit/option/CMakeLists.txt
src/eckit/option/FactoryOption.cc
src/eckit/option/FactoryOption.h
src/eckit/option/MultiValueOption.cc
src/eckit/option/MultiValueOption.h
src/eckit/option/Option.cc
src/eckit/option/SimpleOption.cc
src/eckit/option/SimpleOption.h
src/eckit/option/Title.h
src/eckit/option/VectorOption.cc
src/eckit/option/VectorOption.h

This set of changes resolves build issues specific to Apple Clang 14 (on macOS 13).
Apparently this compiler doesn't work well with inner unnamed namespaces, and doesn't seem to generate the intended linkage symbols. This affected the definition of struct Title, which is a small internal utility to determine the description of an option based on the option type.
The solution was simply to move the Title class to a named namespace.

Correct macOS specific downstream issues ECKIT-620

---

src/eckit/cmd/UserInput.cc
src/eckit/config/ResourceMgr.cc
src/eckit/filesystem/TmpFile.cc

warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]

Compiler warnings re sprintf

---

src/eckit/codec/Metadata.h
src/eckit/codec/types/scalar.cc
src/eckit/config/Configuration.cc
src/eckit/config/Configuration.h
src/eckit/config/LocalConfiguration.cc
src/eckit/config/LocalConfiguration.h
src/eckit/option/CmdArgs.cc
tests/option/eckit_test_option_cmdargs.cc

`const eckit::Value& eckit::Configuration::get()` is "public" and likely abused in various places, leaking the `eckit::Value` abstraction.
This pull request marks this function as deprecated, and warns for it to be removed in a next release.
Further changes to `LocalConfiguration` have been made so that classes like e.g. `eckit::codec::MetaData` or `atlas::Config` which derive from `LocalConfiguration` don't need internal access to `eckit::Value`.
I have modified the `atlas::Config` class respectively and can commit that once this PR is merged.
This relates to PR #101 as without access to `eckit::Value` one will no longer be able to use `eckit::Value` for introspection.

Deprecate access to `const Value& Configuration::get()`

---

src/eckit/geometry/CoordinateHelpers.cc
tests/geometry/test_coordinate_helpers.cc

This modifies `eckit::geometry::normalise_angle`` so that it uses a modulo operator to find the correct output value, rather than repeatedly adding or subtracting 360 from the input. This makes the function orders of magnitude faster for very large input values.
Also added a few additional checks to test_coordinate_helpers to verify that `normalise_angle` works correctly on negative inputs and very large (positive or negative) inputs.
Fixes #102.

Normalise angle fix

---

src/eckit/utils/Regex.cc
src/eckit/utils/Regex.h
tests/utils/CMakeLists.txt
tests/utils/test_regex.cc

In addition to a bug fix with FDB5 we need a mechanism to properly escape regex char from a string.
FDB5 uses paths in regex without escaping special chars. This causes problems for paths with characters like + or *.

Add Regex::escape function to escape special regex chars from a string

---

src/eckit/codec/CMakeLists.txt

This addresses https://github.com/ecmwf/eckit/issues/114 by installing eckit_codec_config.h in the correct place in the install directory.

Correct install location for codec file.

---

src/eckit/mpi/Comm.cc
src/eckit/mpi/Comm.h
src/eckit/mpi/Parallel.cc
src/eckit/mpi/Parallel.h
src/eckit/mpi/ParallelGroup.cc
src/eckit/mpi/ParallelRequest.cc
src/eckit/mpi/Serial.cc
src/eckit/mpi/Serial.h

This PR changes `const char*` arguments into `std::string_view`, so that we can now downstream replace amongst others
```eckit::mpi::setCommDefault( string.c_str() )``` and ```eckit::mpi::comm( string.c_str() )```
with 
```eckit::mpi::setCommDefault( string )``` and ```eckit::mpi::comm( string )```.
It should still be compatible with callers passing `const char*`.

Use std::string_view in eckit_mpi

---

src/eckit/config/Configuration.cc
src/eckit/config/Configuration.h
tests/config/test_configuration.cc

This proposed addition allows to make sure that a configured value is of an expected type without resorting to try / catch.

Add introspection to eckit::Configuration

---

src/eckit/config/Configuration.cc
src/eckit/config/Configuration.h
tests/config/test_configuration.cc

I would like to check properly if a value ina yaml configuration is NULL.
Otherwise I can just guess that a value is null by exclusion (when all the other introspective calls are false).

Add isNull to eckit::Configuration

---

src/eckit/testing/Test.h

Use ref for lambda instead of value, which copies

Fix test macros

---

src/eckit/thread/ThreadSingleton.h

Allows resurrection of dead singletons by enabling  pthread_once to execute after the current instance has been destroyed.

Reset init guard flag in destructor

---

src/eckit/codec/Stream.cc
src/eckit/codec/Stream.h
tests/value/CMakeLists.txt

This fixes a few warnings when compiling eckit on LUMI with CrayClang compiler cce/17.
One warning was for unrecognised flag for CrayClang as opposed to "just" Cray.
Another related to deprecated implicit assignment operator.

Fix compilation warnings on LUMI with cce/17

---

tests/value/test_value_string.cc
tests/value/test_value_typeordering.cc

strcmp has strange return values on aarch64
we can't simply assume it is -1/0/1

fix tests on aarch64

---

src/eckit/log/RotationTarget.cc
src/eckit/types/Time.h

example: seconds in a day would be `eckit::Time::secondsInDay` instead of `86400`

Replaces magic numbers with compile-time variables

---

CMakeLists.txt
src/eckit/linalg/CMakeLists.txt
src/eckit/linalg/detail/HIP.h
src/eckit/linalg/sparse/LinearAlgebraHIP.cc
src/eckit/linalg/sparse/LinearAlgebraHIP.h
tests/linalg/CMakeLists.txt

This is nearly a copy-paste of the just-merged update of the CUDA backend, with the difference that CUDA symbols are replaced with HIP symbols.
A unit-test with the backend is created and succesfully tested on LUMI with AMD GPUs with cce/17.0.1 and rocm/6.0.3

Add HIP backend for LinearAlgebraSparse to support AMD GPUs

---

src/eckit/exception/Exceptions.cc

Exception constructor now respects quiet flag and env variable ECKIT_EXCEPTION_IS_SILENT and no longer logs if any is set.
Fixes: FDB-405

Exception no longer prints to log it set to quiet.

---

src/eckit/utils/Literals.h
tests/utils/CMakeLists.txt
tests/utils/test_literals.cc

Add user defined literals for all 64bit representable power of 2 multi byte units. KiB, MiB, GiB, TiB, PiB and EiB.
Literals are made availabe by including 'utils/Literals.h' and declaring 'using namespace eckit::literals'
Example:
#include <eckit/utils/Literals.h>
using namespace eckit::literals;
const auto bufferSize = 3_KiB;

Add IEC multi-byte unit literals

---

python_wrapper/buildconfig

Disabling Eigen in python wrapper wheel. Our MacOS builder agents do have it -> it sneaks in by default, which is undesirable

Python Wrapper Wheel: no Eigen

---

src/eckit/CMakeLists.txt
src/eckit/log/Bytes.h

This commit also removes Zebi- and Yobibyte static methods from bytes because the result will immediately overflow.
@pmaciel I had a look at checking for wraparound in the added static methods but I decided against it because:
- Unsigned int wraparound is defined behavior in C and C++ (although you can detect it with clangs UB-SAN)
- `Bytes` is used for logging
- Adding a notifying `SafeMultiplication` just for this change seems out of proportion, especially if you want to do this proper you should probably use the available gcc/clang intrinsics `__builtin_uaddll_overflow` et.al. (https://gcc.gnu.org/onlinedocs/gcc-13.3.0/gcc/Integer-Overflow-Builtins.html) BUT ofc the intrinsics are different / not available on INTEL compilers.
Even without explicitly checking the situation is already …

Update Bytes.h to use multi-byte unit literals

---

python_wrapper/buildconfig
python_wrapper/post-build.sh
python_wrapper/pre-compile.sh

Adding `libcurl` as a dependency for eckit, consists of:
- yum installing prerequisite libraries (ssl, psl)
- cloning and building curl (with openssl)
- adding eckit cmake params
- including bundled licenses in the wheel
- calling auditwheel at the end to bundle all libs in (note: we may change this later to manually bundling in, as we had to do with eccodes)
NOTE: the base is not `devel` but `fix/condDeclare` since this one is conditional on it

Python wheel: add curl and proj dependencies

---

.github/workflows/build-wheel-wrapper.yml

This is actually important, because the original action is not updated anymore and thus fails

Python wheel: switch to migrated action repo

---

src/eckit/mpi/Comm.cc
src/eckit/mpi/Parallel.cc

With some MPI implementations a SIGSEGV occurs during `MPI_Finalize()` when invoked after `main()` ends. This is the standard way that `eckit::mpi` operates as the registration of MPI communicators is stored in a global static registry that is destroyed after `main()`.
Consider following C++ program using `eckit::mpi` :
```c++
#include <iostream>
#include "eckit/mpi/Comm.h"
#include "eckit/runtime/Main.h"
int main(int argc, char* argv[]) {
std::cerr << "------ start of main ------" << std::endl;
eckit::Main::initialise(argc,argv);
// MPI gets automatically initialized on first use
int mpi_size = eckit::mpi::comm().size();
// eckit::mpi::finaliseAllComms();
// --> Uncommenting this avoids the problem but is generally not used.
std::cerr << "------ end of main ------" << std::endl;
return …
```

Workaround for SIGSEGV during MPI_Finalize after main() with CUDA-aware MPI

---

tests/geometry/test_polygon.cc

This PR attempts to address issue #71 .
Nested SECTION scopes in `eckit_test_geometry_polygon` unit test were simply ignored.
By fixing this, it exposes that the unit-test was actually faulty with failed `EXPECT`.
Therefore this PR is currently failing and should be fixed further.
@pmaciel if you don't mind I took the liberty to assign you to see how to fix the failing `EXPECT` as this test is in your expertise and development.

Remove nested SECTION in test_polygon.cc (reported in #71)

---

src/eckit/exception/Exceptions.cc
src/eckit/exception/Exceptions.h

Here's a modernisation of the base eckit::Exception class and bundled derived hierarchy. This includes:
- consistent interface among exceptions
- consistent (possible) use of CodeLocation (Here())
- ~~enforce non-copiable, non-movable (we have no case of a use pattern that requires moveability)~~ (some downstream projects are copying exceptions)
- conditional behaviour on the environment guaranteed by assigning conditionals before main()
- fixed mising return, nullptr access and tests
I've done this for some time but just found the motivation to push this ahead of possible changes to exception logging. Whether we do/don't do it, this is rather a cleanup before new code comes in.

Modernise exceptions

---

src/eckit/utils/RLE.cc
src/eckit/utils/RLE.h
tests/utils/CMakeLists.txt
tests/utils/test_rle.cc

added optional timeout to RLEdecode2 (to be used in mars-server layout compression).
As the timeout expires, we copy the remaining input data and return

ECKIT-628 added timeout to RLE encoder

---

src/eckit/utils/SafeCasts.h
tests/utils/CMakeLists.txt
tests/utils/test_safe_casts.cc

Adds new 'into_unsigned()' and 'into_signed' type casts that throw on conversion from a unrepresentable value in the target representation.

Adds safe signed->unsigned, unsigned->signed casts

---

python_wrapper/buildconfig
python_wrapper/post-build.sh
python_wrapper/pre-compile.sh

This adds lz4 dependency on linux, to enable Orca grids
A succ build of wheels: https://github.com/ecmwf/eckit/actions/runs/14218423248

Python wheel: add lz4

---

.github/workflows/build-wheel-wrapper.yml
.github/workflows/cd.yml

1/ exposes `use_test_pypi` option -- with that set to `true`, the action is safe to run from any branch etc. Later I'll add a trigger to test it automatically on eg a PR to `main`
2/ adds wheel building & uploading invocation to tag push
Note: *needs* https://github.com/ecmwf/reusable-workflows/pull/18 merged

Python wheel: add testpypi param, push-tag trigger

---

src/eckit/types/Fraction.cc
src/eckit/types/Fraction.h
tests/types/test_fraction.cc

This fixes an issue with eckit::Fraction on some specific conversions from real values (double). It incrementally relaxes the comparison to determine fraction convergence, a more robust approach in the general case.
There's only behaviour change in the Fraction::Fraction(double).
Note that the original behaviour is also preserved, which is just the first attempt to converge strictly (without relaxation), so this does not incur on any changes of results for already working code (particularly mir.) Instead it only makes some additional specific cases work (found on handling some unstructured grids.)
There is urgency in merging this.

eckit::Fraction improved convergence

---

python_wrapper/post-build.sh

Minor fix in the bash script for wheel building

Python wheel: minor fix

---

python/eckit/build_chain.sh
python/eckit/pyproject.toml
python/eckit/requirements-devel.txt
python/eckit/setup.py

1/ similar changes that we recently did to mir-python
2/ support for local installation of prereq wheels (required for whole-stack-develop release)
3/ dynamic version & dependencies

Python: make eckit build compatible with cd release
